name: First GitHub Action

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest


    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-java@v3
      with:
        distribution: 'temurin' # See 'Supported distributions' for available options
        java-version: '17'

    - name: Permission to Maven
      run: chmod +x mvnw
    

    - name: Build with Maven
      run: cd spring-maven-plugins && ./mvnw -DskipTests=true package

    - name: Run tests
      run: cd spring-maven-plugins && ./mvnw test

    - name: Run prettier
      run: cd spring-maven-plugins && ./mvnw prettier:check